### ISSUE TITLE
Create new spatial tags if they don't exist

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-ed#241]
As a user, I can start the harvesting process manually. In both the source and the target systems we have spatial information for each datasets, which we want to harvest too.

Upon harvesting, the spatial information (a comma separated string) is tokenized and tags are extracted from the values. Those tags belong in the `spatial` tag vocabulary.

The issue is that when the target system does not contain the incoming tag, the fetch queue crashes without trying to create it first.

Acceptance criteria:

- [ ] when the harvested dataset would generate new tags in the `spatial` vocabulary, the new tags should be created
- [ ] the target dataset metadata should contain all the source spatial tags

**Comment by avdata99** [comment]
@nightsh fixed with [this commit](https://github.com/CivicActions/ckanext-ed/commit/32d918276313f8620427706d38885137f87b6d50)

**Comment by avdata99** [comment]
Error raised in test environment.
Notified by @woodt:

```
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: 2020-01-17 12:42:37,745 ERROR [ckanext.datajson.harvester_base] failed to create package edfacts-school-improvement-grant-2010-11 from https://www2.ed.gov/data.json
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: Traceback (most recent call last):
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/usr/lib/ckan/default/bin/paster", line 10, in <module>
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: sys.exit(run())
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: invoke(command, command_name, options, args[1:])
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: exit_code = runner.run(args)
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: result = self.command()
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/apps/ckan/lib/default/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 193, in command
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: fetch_callback(consumer, method, header, body)
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/apps/ckan/lib/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 408, in fetch_callback
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: fetch_and_import_stages(harvester, obj)
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/apps/ckan/lib/default/src/ckanext-harvest/ckanext/harvest/queue.py", line 425, in fetch_and_import_stages
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: success_import = harvester.import_stage(obj)
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/apps/ckan/lib/default/src/ckanext-datajson/ckanext/datajson/harvester_base.py", line 730, in import_stage
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: pkg = get_action('package_create')(self.context(), pkg)
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/apps/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 464, in wrapped
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: result = _action(context, data_dict, **kw)
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: File "/apps/ckan/lib/default/src/ckanext-ed/ckanext/ed/actions.py", line 179, in package_create
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: raise ValidationError(errors)
Jan 17 12:42:37 bpvhxlvcka301 paster[113463]: ckan.logic.ValidationError: {'spatial': [u'Tag U does not belong to vocabulary spatial']}
Jan 17 12:42:37 bpvhxlvcka301 systemd[1]: ckan_harvester_fetch.service: main process exited, code=exited, status=1/FAILURE
Jan 17 12:42:37 bpvhxlvcka301 systemd[1]: Unit ckan_harvester_fetch.service entered failed state.
Jan 17 12:42:37 bpvhxlvcka301 systemd[1]: ckan_harvester_fetch.service failed.
```

**Comment by avdata99** [comment]
I updated the PR. This solution works but we need to check if _spatial_ could be a list of always need to be a string.
